# THIS IS JUST A TEMPLATE 

version: "3.8"

services:
  mongo1:
    container_name: mongo1
    image: mongo:7.0
    command: ["--replSet", "myReplSet", "--bind_ip_all", "--port", "27117", "--keyFile", "/etc/mongodb/pki/keyfile"]
    restart: always
    ports:
      - 27117:27017
    networks:
      mongo-cluster:
        ipv4_address: 111.222.32.2
    volumes:
      - ${PWD}/rs_keyfile:/etc/mongodb/pki/keyfile
      - "mongo1_data:/data/db"
      - "mongo1_config:/data/configdb"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example



  mongo2:
    image: mongo:7.0
    container_name: mongo2
    command: ["--replSet", "rs0" ,"--bind_ip_all", "--port", "27217","--keyFile", "/etc/mongodb/pki/keyfile"]
    restart: always
    ports:
      - 27217:27017
    networks:
      mongo-cluster:
        ipv4_address: 111.222.32.3
    volumes:
      - ${PWD}/rs_keyfile:/etc/mongodb/pki/keyfile
      - "mongo2_data:/data/db"
      - "mongo2_config:/data/configdb"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example



  mongo3:
    image: mongo:7.0
    container_name: mongo3
    command: ["--replSet", "rs0" ,"--bind_ip_all", "--port", "27317","--keyFile", "/etc/mongodb/pki/keyfile"]
    restart: always
    ports:
      - 27317:27017
    networks:
      mongo-cluster:
        ipv4_address: 111.222.32.4
    volumes:
      - ${PWD}/rs_keyfile:/etc/mongodb/pki/keyfile
      - "mongo3_data:/data/db"
      - "mongo3_config:/data/configdb"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example



volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
  mongo1_config:
  mongo2_config:
  mongo3_config:

networks:
  mongo-cluster:
    ipam:
      config:
        - subnet: 111.222.32.0/24